### PR TITLE
Add Localizations support

### PR DESCRIPTION
**Pull request by Cilyena**
I used in-game elements to add language support to the mod.

### CODE REVIEW

**Comment by Cilyena** [comment]
image
image
image
image
image
```
ID,Text,Comment
BeaverBuddies.Menu.JoinCoopGame,"Rejoindre partie co-op","Join co-op game"
BeaverBuddies.JoinCoopGame.EnterIp,"Entrez l'adresse IP de l'hôte :","Enter the global IP address of the Host:"
BeaverBuddies.FirstTimer.Message,"Il semble que vous utilisiez BeaverBuddies pour la première fois. Nous vous recommandons de jeter un coup d'œil rapide à notre guide pour vous assurer que vous êtes prêt à jouer. Voulez-vous le faire maintenant ?","It looks like this is your first time using BeaverBuddies. We recommend taking a quick look through our guide to make sure you are set up to play. Would you like to do that now?"
BeaverBuddies.FirstTimer.GuideURL,"https://github.com/thomaswp/BeaverBuddies/wiki/Installation-and-Running","https://github.com/thomaswp/BeaverBuddies/wiki/Installation-and-Running"
BeaverBuddies.Saving.HostCoopGame,"Héberger partie co-op","Host co-op game"
BeaverBuddies.JoinCoopGame.ConnectionFailedMessageWithError,"La connexion a échoué en raison d'une erreur :
{0}
Souhaitez-vous consulter le guide de dépannage ?","Joining failed with error:
{0}
Would you like to open the troubleshooting guide?"
BeaverBuddies.JoinCoopGame.ConnectionFailedMessage,"Échec de connexion à l'Hôte. Souhaitez-vous consulter le guide de dépannage ?","Failed to connect to Host. Would you like to open the troubleshooting guide?"
BeaverBuddies.JoinCoopGame.TroubleshootingUrl,"https://github.com/thomaswp/BeaverBuddies/wiki/Installation-and-Running#troubleshooting","https://github.com/thomaswp/BeaverBuddies/wiki/Installation-and-Running#troubleshooting"

```

**Comment by Cilyena** [comment]
You can use color inside this file :
```
<GreenHighlight>Hello World</GreenHighlight>
<RedHighlight>Hello World</RedHighlight>
<SolidHighlight>Hello World</SolidHighlight>
<color=#AABBFF>Hello World</color>
```
Example from GreenHighlight :
image

**Comment by Cilyena** [comment]
ServerHostingUtils has also been translated.

**Comment by thomaswp** [comment]
Thanks so much for all your work on this. I've made a few tweaks, but looks good. Merging now. I want to test a bit before deploying, so it'll go out with the next release. But so far no issues on my part.

I did find one message you didn't translate and added it to the English localizations, but not the others (may later if time permits).

**Pull request merged**
