### PR TITLE
Use BepInEx.AssemblyPublicizer for Auto generate Lib for the project

### PR DESCRIPTION
**Pull request by Cilyena**

### CODE REVIEW

**Review by Cilyena — COMMENTED** [review]
Publicize="true" Functionality Added to the project

Nuget : https://www.nuget.org/packages/BepInEx.AssemblyPublicizer
Doc : https://github.com/BepInEx/BepInEx.AssemblyPublicizer

**Comment by thomaswp** [comment]
Hey, thanks for the PR. Can you say a little more about what this does. From the diff, I'm guessing the following:
* You're using https://github.com/BepInEx/BepInEx.AssemblyPublicizer to auto-generate a version of the current Timberborn .dlls that have all publicly accessibly members.
* You're changing the references to these local publicized libraries instead of the nuget package for Timberborn/Unity.
* You're also directly referencing the Harmony mod's .dll instead of the nuget package.

Is that right? I won't be able to test it for a week at least, but if so and it works that'll be a good change. It's nice not to rely on the Timberborn package being updated.

Unrelated, since you seem to know a fair bit about this - do you know why some Harmony patches would fail with the vanilla version that were working fine with the BepInEx version? I'm guessing it's something to do with Harmony vs HarmonyX? If not no worries.

**Comment by Cilyena** [comment]
Before building :
Set the game directory path to **TimberbornPath**.
Extract BepInEx into a directory and set **BepInExPath**.

Changes:
- Include all necessary files in the output directory (HarmonyX BepInEx Version but without BepInEx).
- Add a comment on my changes
- Cleaning up

**Comment by Cilyena** [comment]
Add Localizations folder inside the final directory. I have translate your mod in French.
image

**Comment by thomaswp** [comment]
@Cilyena Thanks so much for this. The locally packaged HarmonyX seems to work quite well, and seems to play well with Harmony or even a second HarmonyX from BepInEx, which is nice.

I've made some changes, which you can see in the PR's commit list. I've merged into the v6 branch. Specifically:
* I moved some of the directory config to a env.props file, so you and I can have different local paths. See the updated README for more
* I saved the ReplayConfig.json from getting deleted on build

I need to test a little bit, but I should be able to deploy it soon.

**Comment by Cilyena** [comment]
>     * I moved some of the directory config to a env.props file, so you and I can have different local paths. See the updated README for more

Very practical. Thanks, I followed your instructions and created my own.

Your project is an excellent idea. I haven't yet had the chance to test it with a friend. I will certainly do so soon. Thank you for your work on this mod.

**Pull request merged**
